### ISSUE TITLE
Permalink not working

### ISSUE THREAD

**Issue by bodhi1970** [Graffino/Custom-Post-Type-Maker#1]
Created a CPT and some posts but the permalink of the posts is always linking to the homepage.
What is wrong?
Example: https://www.ghisleni.ch/mitarbeiter/stefano-ghisleni/

**Comment by zenopopovici** [comment]
Sorry, this is not a support forum for Wordpress. CPT is built for developers, you have to understand how custom posts are working in order to be able to use this plugin.

See: https://codex.wordpress.org/Post_Types

If you have an issue with this plugin please attach error messages, and describe what you're doing.

In this case you just misconfigured the plugin or are not doing custom loops in your templates.
